//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookmark_Manager_Client.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookmark_Manager_Client.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add User ähnelt.
        /// </summary>
        public static string AddNewUserString {
            get {
                return ResourceManager.GetString("AddNewUserString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string AddString {
            get {
                return ResourceManager.GetString("AddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrator ähnelt.
        /// </summary>
        public static string AdministratorString {
            get {
                return ResourceManager.GetString("AdministratorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete bookmark? ähnelt.
        /// </summary>
        public static string BookmarkDeleteQuestionString {
            get {
                return ResourceManager.GetString("BookmarkDeleteQuestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete bookmark ähnelt.
        /// </summary>
        public static string BookmarkDeleteTextString01 {
            get {
                return ResourceManager.GetString("BookmarkDeleteTextString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ? ähnelt.
        /// </summary>
        public static string BookmarkDeleteTextString02 {
            get {
                return ResourceManager.GetString("BookmarkDeleteTextString02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create bookmark ähnelt.
        /// </summary>
        public static string ButtonBookmarkCreateString {
            get {
                return ResourceManager.GetString("ButtonBookmarkCreateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete bookmark ähnelt.
        /// </summary>
        public static string ButtonBookmarkDeleteString {
            get {
                return ResourceManager.GetString("ButtonBookmarkDeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit bookmark ähnelt.
        /// </summary>
        public static string ButtonBookmarkEditString {
            get {
                return ResourceManager.GetString("ButtonBookmarkEditString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in Browser ähnelt.
        /// </summary>
        public static string ButtonBookmarkOpenInBrowserString {
            get {
                return ResourceManager.GetString("ButtonBookmarkOpenInBrowserString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string ButtonCancelString {
            get {
                return ResourceManager.GetString("ButtonCancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create category ähnelt.
        /// </summary>
        public static string ButtonCategoryCreateString {
            get {
                return ResourceManager.GetString("ButtonCategoryCreateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete category ähnelt.
        /// </summary>
        public static string ButtonCategoryDeleteString {
            get {
                return ResourceManager.GetString("ButtonCategoryDeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit category ähnelt.
        /// </summary>
        public static string ButtonCategoryEditString {
            get {
                return ResourceManager.GetString("ButtonCategoryEditString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string ButtonDeleteString {
            get {
                return ResourceManager.GetString("ButtonDeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string ButtonExitString {
            get {
                return ResourceManager.GetString("ButtonExitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string ButtonLoginString {
            get {
                return ResourceManager.GetString("ButtonLoginString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string ButtonSaveString {
            get {
                return ResourceManager.GetString("ButtonSaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string ButtonSettingsString {
            get {
                return ResourceManager.GetString("ButtonSettingsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete category? ähnelt.
        /// </summary>
        public static string CategoryDeleteQuestionString {
            get {
                return ResourceManager.GetString("CategoryDeleteQuestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete category ähnelt.
        /// </summary>
        public static string CategoryDeleteTextString01 {
            get {
                return ResourceManager.GetString("CategoryDeleteTextString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ? All child categories and bookmarks will be deleted. ähnelt.
        /// </summary>
        public static string CategoryDeleteTextString02 {
            get {
                return ResourceManager.GetString("CategoryDeleteTextString02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top category ähnelt.
        /// </summary>
        public static string CategoryIsTopString {
            get {
                return ResourceManager.GetString("CategoryIsTopString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parent category ähnelt.
        /// </summary>
        public static string CategoryParentString {
            get {
                return ResourceManager.GetString("CategoryParentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change password ähnelt.
        /// </summary>
        public static string ChangePasswordString {
            get {
                return ResourceManager.GetString("ChangePasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut ähnelt.
        /// </summary>
        public static string CutString {
            get {
                return ResourceManager.GetString("CutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string EditString {
            get {
                return ResourceManager.GetString("EditString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string EmailString {
            get {
                return ResourceManager.GetString("EmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host ähnelt.
        /// </summary>
        public static string HostString {
            get {
                return ResourceManager.GetString("HostString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert ähnelt.
        /// </summary>
        public static string InsertString {
            get {
                return ResourceManager.GetString("InsertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string PasswordString {
            get {
                return ResourceManager.GetString("PasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        public static string PortString {
            get {
                return ResourceManager.GetString("PortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Private ähnelt.
        /// </summary>
        public static string PrivateString {
            get {
                return ResourceManager.GetString("PrivateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shared ähnelt.
        /// </summary>
        public static string SharedString {
            get {
                return ResourceManager.GetString("SharedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string TitleString {
            get {
                return ResourceManager.GetString("TitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Url ähnelt.
        /// </summary>
        public static string UrlString {
            get {
                return ResourceManager.GetString("UrlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete user? ähnelt.
        /// </summary>
        public static string UserDeleteQuestionString {
            get {
                return ResourceManager.GetString("UserDeleteQuestionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete user ähnelt.
        /// </summary>
        public static string UserDeleteTextString01 {
            get {
                return ResourceManager.GetString("UserDeleteTextString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ? All categories and bookmarks will be deleted. ähnelt.
        /// </summary>
        public static string UserDeleteTextString02 {
            get {
                return ResourceManager.GetString("UserDeleteTextString02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string UsernameString {
            get {
                return ResourceManager.GetString("UsernameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username or email ähnelt.
        /// </summary>
        public static string UserSearchBoxQueryString {
            get {
                return ResourceManager.GetString("UserSearchBoxQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Users ähnelt.
        /// </summary>
        public static string UsersString {
            get {
                return ResourceManager.GetString("UsersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Users with access ähnelt.
        /// </summary>
        public static string UsersWithAccessString {
            get {
                return ResourceManager.GetString("UsersWithAccessString", resourceCulture);
            }
        }
    }
}
